language: go

sudo: required

services:
  - docker

before_install:
  #install consul
  - docker run -d -p 8500:8500 -e CONSUL_BIND_INTERFACE=eth0 -e CONSUL_CLIENT_INTERFACE=eth0 --name=dev-consul consul

go:
  - 1.5
  - 1.6
  - tip

env:
  - GO15VENDOREXPERIMENT=1

script:
  - go test -v ./...
  - bash integration/consul/test.sh