language: go

sudo: required

services:
  - docker

before_install:
  #start consul
  - docker run -d -p 8500:8500 -e CONSUL_BIND_INTERFACE=eth0 -e CONSUL_CLIENT_INTERFACE=eth0 --name=dev-consul consul
  #start etcd
  - docker run -d --name etcdv3 --net=host quay.io/coreos/etcd:v3.0.1
  # Install vault
  - wget https://releases.hashicorp.com/vault/0.6.0/vault_0.6.0_linux_amd64.zip
  - unzip vault_0.6.0_linux_amd64.zip
  - sudo mv vault /bin/
  - vault server -dev &

go:
  - 1.5
  - 1.6
  - tip

env:
  - GO15VENDOREXPERIMENT=1
  - VAULT_ADDR='http://127.0.0.1:8200'

script:
  - ./test
  - bash integration/consul/test.sh
  - bash integration/etcd/test.sh
  - bash integration/file/test.sh
  - bash integration/vault/test.sh