language: go

sudo: required

services:
  - docker

before_install:
  #start consul
  - docker run -d -p 8500:8500 -e CONSUL_BIND_INTERFACE=eth0 -e CONSUL_CLIENT_INTERFACE=eth0 --name=dev-consul consul
  #start etcd
  - docker run -d --name etcdv3 --net=host quay.io/coreos/etcd:v3.0.1

go:
  - 1.5
  - 1.6
  - tip

env:
  - GO15VENDOREXPERIMENT=1

script:
  - go test -v ./...
  - bash integration/consul/test.sh
  - bash integration/etcd/test.sh