#remco.toml
################################################################
# Global configuration
################################################################
log_level = "debug"
log_format = "text"


################################################################
# Resource configuration
################################################################
[[resource]]
  [[resource.template]]
    src = "./integration/templates/basic.conf.tmpl"
    dst = "/tmp/remco-basic-test.conf"

  [resource.backend]
    [resource.backend.vault]
      onetime = true
      auth_type = "token"
      auth_token = "§§token§§"
      node = "http://127.0.0.1:8200"
      keys = [
          "/database/host",
          "/database/password",
          "/database/port",
          "/database/username",
          "/upstream/app1",
          "/upstream/app2",
      ]
