#remco.toml
################################################################
# Global configuration
################################################################
log_level = "debug"
log_format = "text"


################################################################
# Resource configuration
################################################################
[[resource]]
  [[resource.template]]
    src = "./integration/templates/basic.conf.tmpl"
    dst = "/tmp/remco-basic-test.conf"

  [resource.backend]
    [resource.backend.file]
      onetime = true
      filepath = "./integration/file/config.yml"
      httpheader = { X-Test-Token = "XXX", X-Test-Token2 = "YYY" }
      keys = ["/"]
