baseurl = "https://heavyhorst.github.io/remco/"
languageCode = "en-us"
title = "Remco Docs"
theme = "hugo-theme-learn"
metadataformat = "yaml"
canonifyurls = true
relativeURLs = true

[params]
    menu = ["details", "config", "template", "plugins"]

	# General information
	author = "The remco authors"
	description = "remco is a lightweight configuration management tool"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/HeavyHorst/remco"

	version = "v0.8.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "heavyhorst"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
