[[config]]
  [config.cmd]
    check = ""
    reload = ""

  [[config.template]]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg"

  [config.backend]
    [config.backend.etcdconfig]
      nodes = ["127.0.0.1:2379"]
      watch = true
      prefix = "/"
      version = 3
      interval = 1
      keys = ["/"]

    [config.backend.fileconfig]
      watch = true
      filepath = "/home/rkaufmann/test.yml"
      prefix = "/"
      interval = 1
      keys = ["/"]
