#remco.toml
################################################################
# Global configuration
################################################################
log-level = "debug"


################################################################
# Resource configuration
################################################################
[[resource]]
  [[resource.template]]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg"
    checkCmd = "echo 'check'"
    reloadCmd = "echo 'reload'"

  [resource.backend]
    [resource.backend.etcdconfig]
      nodes = ["127.0.0.1:2379"]
      watch = true
      prefix = "/"
      version = 3
      interval = 1
      keys = ["/"]

    [resource.backend.fileconfig]
      watch = true
      filepath = "/home/rkaufmann/test.yml"
      prefix = "/"
      interval = 1
      keys = ["/"]
