#remco.toml
################################################################
# Global configuration
################################################################
log-level = "debug"
log-format = "text"


################################################################
# Resource configuration
################################################################
[[resource]]
  [[resource.template]]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg"
    checkCmd = ""
    reloadCmd = ""
    mode = "0644"

  [resource.backend]
    [resource.backend.etcdconfig]
      nodes = ["127.0.0.1:2379"]
      #watch = true
      prefix = "/"
      version = 3
      onetime = true
      interval = 1
      keys = ["/"]

    #[resource.backend.fileconfig]
      ## watch = true
      #onetime = true
      #filepath = "/home/rkaufmann/test.yml"
      #prefix = "/"
      #interval = 1
      #keys = ["/"]
