[[config]]
  [config.cmd]
    check = ""
    reload = ""

  [[config.template]]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg2"

  [config.backend]
    [config.backend.etcdconfig]
      nodes = ["http://127.0.0.1:4001"]
      watch = true
      prefix = "/"
      version = 2
      interval = 1
      keys = ["/"]

    [config.backend.fileconfig]
      watch = true
      filepath = "/home/rkaufmann/test.yml"
      prefix = "/hallo"
      interval = 5
      keys = ["/"]