[[config]]
  fileMode = "0644"
  
  [config.cmd]
    check = ""
    reload = ""

  [config.template]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg"

  [config.backend]
    watch = true
    name = "etcd"
    prefix = "/"
    keys = ["/"]
    [config.backend.etcdconfig]
      nodes = ["http://127.0.0.1:4001"]
      version = 2


[[config]]
  fileMode = "0644"
  
  [config.cmd]
    check = ""
    reload = ""

  [config.template]
    src = "/etc/confd/templates/test.cfg"
    dst = "/home/rkaufmann/haproxy.cfg2"

  [config.backend]
    name = "file"
    prefix = "/"
    interval = 5
    keys = ["/"]
    [config.backend.fileconfig]
      filepath = "/home/rkaufmann/test.yml"
    
      