#remco.toml
################################################################
# Global configuration
################################################################
log_level = "debug"
log_format = "text"


################################################################
# Resource configuration
################################################################
[[resource]]
  [[resource.template]]
    src = "./integration/templates/basic.conf.tmpl"
    dst = "/tmp/remco-basic-test-etcdv3.conf"

  [resource.backend]
    [resource.backend.etcdconfig]
      nodes = ["127.0.0.1:2379"]
      prefix = "/appdata"
      version = 3
      onetime = true
      keys = ["/"]

[[resource]]
  [[resource.template]]
    src = "./integration/templates/basic.conf.tmpl"
    dst = "/tmp/remco-basic-test-etcdv2.conf"

  [resource.backend]
    [resource.backend.etcdconfig]
      nodes = ["http://127.0.0.1:2379"]
      prefix = "/appdata"
      version = 2
      onetime = true
      keys = ["/"]
